### ISSUE TITLE
Compatibilidad con MySQL 5.6

### ISSUE THREAD

**Issue by mi-lopez** [SowerPHP/sowerphp#2]
Estimado,

Según el documento de instalación se indica que las bases de datos con las que se trabaja SowerPHP son PostgreSQL o MariaDB. ¿Es posible que SowerPHP se pueda conectar a bases de datos MySQL?. Si es que fuese posible, ¿que nivel de complejidad tiene hacer este cambio?.

Muchas gracias.

**Comment by estebandelaf** [comment]
Si, es posible, de hecho lo hace. Funciona con PostgresSQL, MariaDB, MySQL y SQLite. Debes cambiar el driver en la configuración de la base de datos, en tu caso sería "MySQL". Pero ojo, que si dejas MariaDB también funciona, ya que el driver es el mismo (de hecho el Driver de MySQL e es el que se usa para MariaDB). Saludos!
