### ISSUE TITLE
Call to undefined method sowerphp\core\Network_Email::setDebug()

### ISSUE THREAD

**Issue by airibarren82** [SowerPHP/sowerphp#5]
Al realizar una prueba de correo SMTP me genera el siguiente error

exception:
Error

message:
Call to undefined method sowerphp\core\Network_Email::setDebug()

trace:
#0 [internal function]: website\Dte\Controller_Contribuyentes->config_email_test('666666666', 'sii', 'smtp')
#1 DIR_FRAMEWORK/lib/sowerphp/core/Controller.php(189): ReflectionMethod->invokeArgs(Object(website\Dte\Controller_Contribuyentes), Array)
#2 DIR_FRAMEWORK/lib/sowerphp/core/Routing/Dispatcher.php(179): sowerphp\core\Controller->invokeAction()
#3 DIR_FRAMEWORK/lib/sowerphp/core/Routing/Dispatcher.php(72): sowerphp\core\Routing_Dispatcher::_invoke(Object(website\Dte\Controller_Contribuyentes), Object(sowerphp\core\Network_Request), Object(sowerphp\core\Network_Response))
#4 DIR_WEBSITE/webroot/index.php(54): sowerphp\core\Routing_Dispatcher::dispatch()
#5 {main}

code:
0

**Comment by estebandelaf** [comment]
El error es generado por una aplicación que usa SowerPHP pero no es de SowerPHP. No es un error asociado a este repositorio.
